name: Automated Code Review

on:
  pull_request:
    branches: [ "main" ]

jobs:
  linter:
    name: Checkstyle Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkstyle with Reviewdog
        uses: reviewdog/action-checkstyle@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning